server:
  port: 8901

spring:
  application:
    name: ycwl-file-service
  profiles:
    active: dev

eureka:
  instance:
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:20881/eureka/

file:
  store:
#    type: local
    type: qiniu

qiniu:
  accessKey: 7JjEqYC7MVNNZBthhBAlJUClmRh3JCZr5WDrwLhV
  secretKey: jVNICu_l7LAWbPexfaIKWZd6XEKdvnaBNFZ2Y9ud
  bucketName: ailepet